server:
  port: 9080

spring:
  application:
    name: spring-ai-demo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
      embedding:
        options:
          model: nomic-embed-text
